[phases.setup]
nixPkgs = ["chromium", "nss", "freetype", "fontconfig"]

[phases.install]
cmds = ["npm install --omit=dev"]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/chromium/bin/chromium"

[start]
cmd = "node index.js"
